export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL"

export const GET_ALL_FOLLOWERS_REQUEST = "GET_ALL_FOLLOWERS_REQUEST"
export const GET_ALL_FOLLOWERS_SUCCESS = "GET_ALL_FOLLOWERS_SUCCESS"
export const GET_ALL_FOLLOWERS_FAIL = "GET_ALL_FOLLOWERS_FAIL"

export const GET_ALL_FOLLOWERS_POST_REQUEST = "GET_ALL_FOLLOWERS_POST_REQUEST"
export const GET_ALL_FOLLOWERS_POST_SUCCESS = "GET_ALL_FOLLOWERS_POST_SUCCESS"
export const GET_ALL_FOLLOWERS_POST_FAIL = "GET_ALL_FOLLOWERS_POST_FAIL"