export const ADD_POST_REQUEST = "ADD_POST_REQUEST"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAIL = "ADD_POST_FAIL"

export const GET_LOGIN_USER_POST_REQUEST = "GET_LOGIN_USER_POST_REQUEST"
export const GET_LOGIN_USER_POST_SUCCESS = "GET_LOGIN_USER_POST_SUCCESS"
export const GET_LOGIN_USER_POST_FAIL = "GET_LOGIN_USER_POST_FAIL"

export const HANDLE_LIKE_REQUEST = "HANDLE_LIKE_REQUEST"
export const HANDLE_LIKE_SUCCESS = "HANDLE_LIKE_SUCCESS"
export const HANDLE_LIKE_FAIL = "HANDLE_LIKE_FAIL"

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL"