export const CHECK_USERNAME_REQUEST = "CHECK_USERNAME_REQUEST"
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS"
export const CHECK_USERNAME_FAIL = "CHECK_USERNAME_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"