export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"

export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST"
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS"
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const DEACTIVATE_ACCOUNT_REQUEST = "DEACTIVATE_ACCOUNT_REQUEST"
export const DEACTIVATE_ACCOUNT_SUCCESS = "DEACTIVATE_ACCOUNT_SUCCESS"
export const DEACTIVATE_ACCOUNT_FAIL = "DEACTIVATE_ACCOUNT_FAIL"